const StudentType = {
    FETCH_ALL_STUDENTS : "FETCH_ALL_STUDENTS",
    FETCH_STUDENT: "FETCH_STUDENT",
    CREATE_NEW_STUDENT : "CREATE_NEW_STUDENT",
    DELETE_STUDENT : "DELETE_STUDENT",
}

export default StudentType;