const CampusType = {
    FETCH_ALL_CAMPUSES : "FETCH_ALL_CAMPUSES",
    FETCH_CAMPUS : "FETCH_CAMPUS",
    DELETE_CAMPUS : "DELETE_CAMPUS",
    EDIT_CAMPUS : "EDIT_CAMPUS",
    CREATE_NEW_CAMPUS : "CREATE_NEW_CAMPUS",
};

export default CampusType;